### ISSUE TITLE
Check if WASI deps can be now directly got from wa.dev by cargo-component

### ISSUE THREAD

**Issue by vigoo** [golemcloud/golem#333]
If it works, we need to update the `golem-examples` and the docs

**Comment by vigoo** [comment]
Not working with cargo-component 0.7.0, recheck after update:

```toml
[package.metadata.component.registries]
wasi = "https://wasi.wa.dev"

[package.metadata.component.target]
path = "wit"

[package.metadata.component.target.dependencies]
"wasi:sockets" = { version = "0.2.0", registry = "wasi" }
"wasi:io" = { version = "0.2.0", registry = "wasi" }
"wasi:clocks" = { version = "0.2.0", registry = "wasi" }
```
